name: deploy poor-ui website
on:
  push:
    branches:
      - main

jobs:
  master-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.18.1"

      - name: Install dependencies
        run: yarn install

      - name: Build Website
        run: yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DEPLOY_KEY }}
          branch: gh-pages
          folder: dist
          git-config-name: denghua
          git-config-email: denghua.fm@foxmail.com
          commit-message: poor-ui website deploy done
